name: gerobakgo_with_api
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  flutter_dotenv: ^5.2.1
  go_router: ^16.0.0
  image_picker: ^1.1.2
  flutter_map: ^8.1.1
  pusher_channels_flutter: ^2.4.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env
